import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Link from "next/link";

import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Recipes | Marley Spoon",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="py-8">
          <Link href="/">
            <h1 className="text-4xl font-bold text-center">Recipes</h1>
          </Link>
        </div>
        {children}
      </body>
    </html>
  );
}
